version: '3.7'

services:
  redis:
    restart: always
    image: redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  worker:
    restart: always
    build: .
    command: ['celery', '--workdir=./', '-A', 'project', 'worker']

volumes:
  redis:
  postgres_data: