# Generated by Django 4.1.5 on 2023-01-12 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_country_id_alter_country_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
    ]
